services:
  postgres:
    image: postgres
    hostname: postgres.local
    container_name: postgres.local
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: s3c4Et
    volumes:
      - "./modules/attribution-service/src/test/resources/postgres:/docker-entrypoint-initdb.d"

  adminer:
    image: adminer
    hostname: adminer.local
    container_name: adminer.local
    ports:
      - "8082:8080"

  attribution-service:
    image: ghcr.io/etorres/attribution-service:1.0.0
    hostname: attribution-service.local
    container_name: attribution-service.local
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      ATTRIBUTION_HTTP_SERVER_HOST: "0.0.0.0"
      ATTRIBUTION_JDBC_CONNECT_URL: "jdbc:postgresql://postgres.local:5432/attribution"
      ATTRIBUTION_JDBC_USERNAME: "test"
      ATTRIBUTION_JDBC_PASSWORD: "changeMe"
    restart: unless-stopped
