services:
  attribution-service:
    image: attribution-service:1.0.0
    hostname: attribution-service.test
    container_name: attribution-service.test
    ports:
      - "8080:8080"
    environment:
      ATTRIBUTION_HTTP_SERVER_HOST: "0.0.0.0"
    restart: unless-stopped
