services:
  drift-canary:
    image: drift-canary:1.0.0
    # hostname: drift-canary.test
    container_name: drift-canary.test
    ports:
      - "8080:8080"
    environment:
      ATTRIBUTION_HTTP_HOST: "0.0.0.0"
    restart: unless-stopped
