services:
  postgres:
    image: postgres
    container_name: postgres.local
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: attribution
      POSTGRES_PASSWORD: s3c4Et

  adminer:
    image: adminer
    container_name: adminer.local
    ports:
      - "8082:8080"

  attribution-service:
    image: ghcr.io/etorres/attribution-service:1.0.0
    hostname: attribution-service.local
    container_name: attribution-service.local
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: "-XX:ActiveProcessorCount=2"
      ATTRIBUTION_HTTP_SERVER_HOST: "0.0.0.0"
      ATTRIBUTION_JDBC_CONNECT_URL: "jdbc:postgresql://localhost:5432/attribution"
      ATTRIBUTION_JDBC_USERNAME: "attribution"
      ATTRIBUTION_JDBC_PASSWORD: "s3c4Et"
    restart: unless-stopped
